Repository TeamFlos/phira, pull requests merged in 2025-01, with the labels that each got.

#468 Update ko-KR
  phira/locales/ko-KR/common.ftl
  phira/locales/ko-KR/home.ftl
  phira/locales/ko-KR/settings.ftl
Labels: i18n&L10n

#394 chore(L10n): update zh-TW translation
  phira/locales/zh-TW/common.ftl
  phira/locales/zh-TW/resource.ftl
  phira/locales/zh-TW/settings.ftl
  prpr/locales/zh-TW/parser.ftl
Labels: i18n&L10n

#410 chore(L10n): Improve en-US translation.
  phira/locales/en-US/chart_order.ftl
  phira/locales/en-US/collection.ftl
  phira/locales/en-US/common.ftl
  phira/locales/en-US/event.ftl
  phira/locales/en-US/home.ftl
  phira/locales/en-US/import.ftl
  phira/locales/en-US/library.ftl
  phira/locales/en-US/local.ftl
  phira/locales/en-US/login.ftl
  phira/locales/en-US/message.ftl
  phira/locales/en-US/multiplayer.ftl
  phira/locales/en-US/profile.ftl
  phira/locales/en-US/rate.ftl
  phira/locales/en-US/resource.ftl
  phira/locales/en-US/respack.ftl
  phira/locales/en-US/settings.ftl
  phira/locales/en-US/song.ftl
  phira/locales/en-US/tags.ftl
  prpr/locales/en-US/chart_info.ftl
  prpr/locales/en-US/dialog.ftl
  prpr/locales/en-US/ending.ftl
  prpr/locales/en-US/game.ftl
  prpr/locales/en-US/parser.ftl
  prpr/locales/en-US/scene.ftl
Labels: i18n&L10n

#474 feat: multiline text
  prpr/src/core/line.rs
Labels: enhancement

#433 Improve ru-RU translation (by 丝绸)
  phira/locales/ru-RU/multiplayer.ftl
  phira/locales/ru-RU/profile.ftl
  phira/locales/ru-RU/settings.ftl
  phira/locales/ru-RU/song.ftl
  prpr/locales/ru-RU/chart_info.ftl
  prpr/locales/ru-RU/ending.ftl
  prpr/locales/ru-RU/game.ftl
  prpr/locales/ru-RU/parser.ftl
Labels: i18n&L10n

#498 Thai localization update: setting.ftl
  phira/locales/th-TH/settings.ftl
Labels: i18n&L10n

#490 Update README-zh_CN.md
  README-zh_CN.md
Labels: documentation

#481 chore(L10n): Update zh-TW translation
  phira/locales/zh-TW/settings.ftl
Labels: i18n&L10n

#487 Update French translation
  phira/locales/fr-FR/chapter.ftl
  phira/locales/fr-FR/collection.ftl
  phira/locales/fr-FR/common.ftl
  phira/locales/fr-FR/event.ftl
  phira/locales/fr-FR/home.ftl
  phira/locales/fr-FR/library.ftl
  phira/locales/fr-FR/local.ftl
  phira/locales/fr-FR/login.ftl
  phira/locales/fr-FR/multiplayer.ftl
  phira/locales/fr-FR/profile.ftl
  phira/locales/fr-FR/rate.ftl
  phira/locales/fr-FR/resource.ftl
  phira/locales/fr-FR/respack.ftl
  phira/locales/fr-FR/settings.ftl
  phira/locales/fr-FR/song.ftl
  phira/locales/fr-FR/tags.ftl
Labels: i18n&L10n

#467 feat: support parent chain
  prpr/src/core/line.rs
  prpr/src/parse/rpe.rs
Labels: bug, enhancement
